apiVersion: "agones.dev/v1"
kind: Fleet
metadata:
  name: game-server-fleet
spec:
  replicas: 2
  template:
    spec:
      ports:
        - name: default
          portPolicy: Dynamic
          containerPort: 39999
          protocol: TCPUDP
      health:
        initialDelaySeconds: 6
        periodSeconds: 6
      template:
        spec:
          containers:
            - name: game-server
              image: game-server:latest
              imagePullPolicy: Never
              